### ISSUE TITLE
Support Min, Max to capture stats

### ISSUE THREAD

**Issue by loranger2k** [googleforgames/open-saves#121] opened 2020-09-14 22:25 UTC
**Is your feature request related to a problem? Please describe.**
Ability to capture statistics from game clients in high concurrent environments.

**Describe the solution you'd like**
We'd like to see new endpoints in Triton to perform atomic operation to increment, decrement, find min, and find max values based on query parameters and what's stored in the DB.

**Describe alternatives you've considered**
The alternative would be to capture the incoming stat requests into a queue in a front-end gateway to perform sequential operations on the database to ensure data is not overwritten or lost become of high concurrency.

**Additional context**

**Comment by yuryu** [comment] 2021-05-03 21:19
We can use this method here:

https://stackoverflow.com/questions/29629274/how-do-i-find-a-max-value-in-datastore

**Comment by yuryu** [comment] 2021-05-03 21:24
Atomic operations will be discussed in #134

**Comment by yuryu** [comment] 2021-05-11 17:59
According our offline discussion this week, we want to implement a "keep max or min" update method. The goal is to keep the biggest (or smallest) value in the database and not to query the biggest value.

**Comment by yuryu** [comment] 2021-09-14 23:44
Marked as duplicate of #134. Let me know if we need a separate query function.

**Closed by yuryu** 2021-09-14 23:44 UTC
Labels: duplicate, enhancement
